### PR TITLE
Game World

### PR DESCRIPTION
**Pull request by Peter-Scheelke**
The game world is done. It passes StyleCop, has almost 100% coverage, blah blah blah.

I also had to change the dictionary slightly to avoid having to deal with relative file paths.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/sh4ne/Scrabble_CS3450/pull/58" target="_blank">ReviewNinja

**Comment by Peter-Scheelke** [comment]
Obligatory :+1:

**Comment by johnsonjo4531** [comment]
Very Nice! :+1:

**Comment by sh4ne** [comment]
:+1: nice! Let's merge this bad boy.

**Pull request merged**
