### PR TITLE
Logger class

### PR DESCRIPTION
**Pull request by sh4ne**
In response to https://github.com/sh4ne/Scrabble_CS3450/issues/6. This is the logger class. To access log files go to LocalGitRepo/Scrabble/bin/Debug/Logs or  LocalGitRepo/Scrabble/bin/Release/Logs. I have made changes to the GUI so we could test it out. Please make use of these so we can debug our problems more easily later. Thanks!

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/sh4ne/Scrabble_CS3450/pull/40" target="_blank">ReviewNinja

**Comment by sh4ne** [comment]
I haven't figured out the unit tests yet, I will make an issue and assign myself to it.

**Comment by sh4ne** [comment]
:+1:

**Comment by Peter-Scheelke** [comment]
It'll need documentation/unit tests, but other than that, it looks fine.

**Comment by sh4ne** [comment]
what documentation does it need?

**Comment by Peter-Scheelke** [comment]
Oh, I was looking at the code for the main form. The logger code looks like it has the correct documentation. :+1:

**Comment by joshcv2112** [comment]
:+1:

**Comment by sh4ne** [comment]
I'm working on the unit tests so I won't merge this until those are done.

**Comment by murple13** [comment]
:+1:

**Comment by sh4ne** [comment]
Just added the unit tests

**Pull request merged**
