### PR TITLE
Modified Play Class

### PR DESCRIPTION
**Pull request by johnsonjo4531**
I did these a while ago. It adds new exceptions for when play is created and checks whether the play is horizontal or vertical. It also makes the Play Class have 100% code coverage. It may have decreased the code coverage in the board class though due to some issues there being solved in this Play class. I had to modify the board class unit tests. 

Thoughts?

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/sh4ne/Scrabble_CS3450/pull/52" target="_blank">ReviewNinja

**Comment by johnsonjo4531** [comment]
:+1:

**Comment by Peter-Scheelke** [comment]
:+1: Looks fine.

**Comment by sh4ne** [comment]
:+1:

**Pull request merged**
