### PR TITLE
added mock ups

### PR DESCRIPTION
**Pull request by Peter-Scheelke**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/sh4ne/Scrabble_CS3450/pull/47" target="_blank">ReviewNinja

**Comment by Peter-Scheelke** [comment]
:+1:

**Comment by sh4ne** [comment]
Do we want to merge this?

**Comment by joshcv2112** [comment]
:+1:

**Comment by murple13** [comment]
:+1:

**Pull request merged**
