### PR TITLE
GameBoardSquare and LetterTile Classes

### PR DESCRIPTION
**Pull request by Peter-Scheelke**
I have created GameBoardSquare and LetterTile classes.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/sh4ne/Scrabble_CS3450/pull/29" target="_blank">ReviewNinja

**Comment by Peter-Scheelke** [comment]
Hallelujah, it looks like this pull request actually worked . . .

The changes I've made pass Stylecop. Also, I suggest taking a look at this: http://xkcd.com/1597/.

**Comment by sh4ne** [comment]
I am glad that you figured it out! Have you merged these files with the current sh4ne/master? That will review hopefully fix the merge conflicts.

**Comment by Peter-Scheelke** [comment]
I have not. Shouldn't that wait till after the code review?

**Comment by sh4ne** [comment]
You will need to merge your changes with the latest sh4ne/master. that doesn't update the main master, it will just update your branch with the latest changes.

**Comment by Peter-Scheelke** [comment]
Okay, I'm not entirely sure how to do that.

**Comment by sh4ne** [comment]
so, this has been merged in, we will just say everyone code reviewed it. :) :+1:

**Pull request closed without merging**
