### PR TITLE
I think this will merge the main repository into mine. Let's see . . .

### PR DESCRIPTION
**Pull request by Peter-Scheelke**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/sh4ne/Scrabble_CS3450/pull/55" target="_blank">ReviewNinja

**Comment by Peter-Scheelke** [comment]
Hmm, apparently that doesn't happen without changing the main repository. Anyway, I've done a bunch of stuff with the GameWorld class. It's mostly done (although its test coverage isn't very good).

**Comment by Peter-Scheelke** [comment]
Bye!

**Comment by Peter-Scheelke** [comment]
You're welcome, John.

**Pull request closed without merging**
