### PR TITLE
Dictionaryunittest

### PR DESCRIPTION
**Pull request by murple13**
Unit test for the dictionary class and GUI for the board class.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/sh4ne/Scrabble_CS3450/pull/51" target="_blank">ReviewNinja

**Comment by Peter-Scheelke** [comment]
:+1:

**Comment by johnsonjo4531** [comment]
:+1:

**Comment by sh4ne** [comment]
:+1:

**Comment by sh4ne** [comment]
merged in this request. https://github.com/sh4ne/Scrabble_CS3450/pull/53

**Pull request merged**
