### PR TITLE
Server and Client GUIs

### PR DESCRIPTION
**Pull request by sh4ne**
I have gotten a base for the server and client ready. Still not perfect... but good enough to have a base for the Client Gui

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/sh4ne/Scrabble_CS3450/pull/49" target="_blank">ReviewNinja

**Comment by johnsonjo4531** [comment]
:+1:

**Comment by murple13** [comment]
:+1:

**Comment by Peter-Scheelke** [comment]
:+1:

**Pull request merged**
