### PR TITLE
ChatPacket object, and empty GameWorld object and Bag.

### PR DESCRIPTION
**Pull request by Peter-Scheelke**
I created an empty GameWorld object, as well as a ChatPacket object (as well as unit tests for ChatPacket). Both pass stylecop.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/sh4ne/Scrabble_CS3450/pull/44" target="_blank">ReviewNinja

**Comment by Peter-Scheelke** [comment]
Obligatory :+1:

**Comment by sh4ne** [comment]
cool beans!

I removed your +1 because I added more stuff.

**Comment by Peter-Scheelke** [comment]
I added the Bag, and accompanying unit tests.

**Comment by sh4ne** [comment]
:+1: thank you, ill merge this in before class

**Pull request merged**
