### PR TITLE
Logger class

### PR DESCRIPTION
**Pull request by sh4ne**
added networking capabilities, logger stuff

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/sh4ne/Scrabble_CS3450/pull/35" target="_blank">ReviewNinja

**Comment by sh4ne** [comment]
:+1:

**Comment by Peter-Scheelke** [comment]
:+1:

**Comment by sh4ne** [comment]
@johnsonjo4531 @murple13 @joshcv2112 can you hurry and "review" this meaning just accept it so we can use it in today's class

**Comment by johnsonjo4531** [comment]
:+1:

**Comment by murple13** [comment]
:+1:

**Pull request merged**
